stages:
- name: Build & Push
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: salalemdockerhub/course-builder-bff:${CICD_GIT_BRANCH}-${CICD_GIT_COMMIT}
      pushRemote: true
      registry: index.docker.io
timeout: 60
notification: {}
