stages:
- name: Build & Publish Production Release
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: salalemdockerhub/transformed-federated-service-runner:${CICD_GIT_TAG}
      pushRemote: true
      registry: index.docker.io
    when:
      event:
        include:
        - tag
  when:
    branch:
      include:
      - master
    event:
      include:
      - tag
- name: Build & Publish Branch Release
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: salalemdockerhub/transformed-federated-service-runner:${CICD_GIT_BRANCH}-${CICD_GIT_COMMIT}
      pushRemote: true
      registry: index.docker.io
    when:
      branch:
        include:
        - staging
      event:
        include:
        - push
  when:
    branch:
      include:
      - master
      - staging
    event:
      include:
      - push
timeout: 60
notification: {}
